=== mi1069/WBA2/Phase _1/Aufgabe_3/Kuchen_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Kuchen_Schema"
	xmlns:xs="http://www.example.org/Kuchen_Schema" elementFormDefault="qualified">

	<!-- Elemente -->
	<element name="collection" type="xs:collection_type" />
	<element name="rezept" type="xs:rezept_type" />
	<element name="rezept-id" type="int" />
	<element name="title" type="string" />
	<element name="autor" type="string" />
	<element name="date" type="dateTime" />
	<element name="picture" type="xs:picture_type" />
	<element name="ingrediens" type="xs:ingrediens_type" />
	<element name="ingredient" type="xs:ingredient_type" />
	<element name="preparation" type="xs:preparation_type" />
	<element name="step" type="string" />
	<element name="comments" type="xs:comments_type" />
	<element name="comment" type="xs:comment_type" />
	<element name="text" type="string" />
	<element type="string" name="arbeitszeit" />
	<element type="string" name="schwierigkeitsgrad" />
	<element type="string" name="brennwert" />

	<!-- Attribute -->
	<attribute name="name" type="string" />
	<attribute name="amount" type="float" />
	<attribute name="unit" type="string" />
	<attribute name="uri" type="anyURI" />
	<attribute name="portion" type="int" />



	<!-- Sammlung von Rezepten -->
	<complexType name="collection_type">
		<sequence>
			<element ref="xs:rezept" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<!-- Rezept -->
	<complexType name="rezept_type">
		<sequence>
			<element ref="xs:rezept-id" />
			<element ref="xs:title" />
			<element ref="xs:autor" />
			<element ref="xs:date" />
			<element ref="xs:picture" minOccurs="0" maxOccurs="unbounded" />
			<element ref="xs:ingrediens" />
			<element ref="xs:preparation" />
			<element ref="xs:comment" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>


	<!-- Pictures -->
	<complexType name="picture_type">
		<attribute ref="xs:uri" use="optional" />
	</complexType>

	<!-- Zutat -->
	<complexType name="ingredient_type">
		<attribute ref="xs:name" />
		<attribute ref="xs:amount" />
		<attribute ref="xs:unit" />
	</complexType>

	<!-- Zutaten -->
	<complexType name="ingrediens_type">
		<sequence>
			<element ref="xs:ingredient" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute ref="xs:portion" />
	</complexType>

	<!-- Zubreitung -->
	<complexType name="preparation_type">
		<sequence>
			<element ref="xs:arbeitszeit" />
			<element ref="xs:schwierigkeitsgrad" />
			<element ref="xs:brennwert" />
			<element ref="xs:step" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>


	<!-- Kommentare -->
	<complexType name="comment_type">
		<sequence>
			<element ref="xs:autor" />
			<element ref="xs:date" />
			<element ref="xs:text" />
			<element ref="xs:picture" />
		</sequence>
	</complexType>

	<complexType name="comments_type">
		<sequence>
			<element ref="xs:comment" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
</schema>

=== mi1069/WBA2/Phase 1/src/Aufgabe 3 - Rezept/Rezepte.xml
<?xml version="1.0" encoding="UTF-8"?>

<xs:collection xmlns:xs="http://www.example.org/Kuchen_Schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Kuchen_Schema Kuchen_Schema.xsd ">

	<!-- 1 Rezept: Carpaccio vom Rind -->
	<xs:rezept>
		<xs:rezept-id>101</xs:rezept-id>
		<xs:title>xs:Carpaccio vom Rind</xs:title>
		<xs:autor>xs:francette</xs:autor>
		<xs:date>2007-10-18T12:00:00</xs:date>
		<xs:picture
			xs:uri="http://static.chefkoch-cdn.de/ck.de/rezepte/87/87373/504604-960x720-carpaccio-vom-rind.jpg" />
		<xs:ingrediens xs:portion="4">
			<xs:ingredient 
				xs:name="Rinderfilet, oder Roastbeef, hauchdünn geschnitten"
				xs:amount="400" xs:unit="g" />
			<xs:ingredient xs:name="Rucola" xs:amount="1" xs:unit="Pck" />
			<xs:ingredient xs:name="Parmesan, frisch gehobelt"
				xs:amount="1"  xs:unit="Stück" />
			<xs:ingredient xs:name="Zitrone(n), den Saft" xs:amount="2" />
			<xs:ingredient xs:name="Pinienkerne"
				xs:amount="100" xs:unit="g" />
			<xs:ingredient xs:name="Balsamico" />
			<xs:ingredient xs:name="Olivenöl" />
			<xs:ingredient xs:name="Pfeffer, schwarz, aus der Mühle" />
			<xs:ingredient xs:name="Meersalz" />
			<xs:ingredient xs:name="Baguette" />
		</xs:ingrediens>
		<xs:preparation>
			<xs:arbeitszeit>cs.15 Min.</xs:arbeitszeit>
			<xs:schwierigkeitsgrad>pfiffig</xs:schwierigkeitsgrad>
			<xs:brennwert>keine Angabe</xs:brennwert>
			<xs:step>4 Teller mit Balsamico beträufeln und mit einem Pinsel verteilen, so dass der gesamte Teller dünn bedeckt ist. </xs:step>
			<xs:step>Die Pinienkerne anrösten und den Rucola waschen.</xs:step>
			<xs:step>Die dünnen Rinderfilet-Scheiben, den Rucola und die Pinienkerne auf die Teller geben, und den Parmesan hauchdünn darüber hobeln.</xs:step>
			<xs:step>Jetzt mit Salz, Zitronensaft und Pfeffer würzen, das Olivenöl darüber träufeln. Ich nehme auch noch etwas Balsamico dazu</xs:step>
			<xs:step>Dann in sofort mit dem Baguette servieren.</xs:step>
		</xs:preparation>
		<xs:comment>
			<xs:autor>Kristina_1978</xs:autor>
			<xs:date>2008-03-29T22:16:00</xs:date>
			<xs:text>Exzellent, liebe Francette! :-) Und Deine Aufnahme davon ist ebenfalls eine Augenweide!</xs:text>
			<xs:picture
				xs:uri="http://static.chefkoch-cdn.de/ck.de/user/0c3c975008502106072d8ec6d7ed2633.jpg" />
		</xs:comment>
	</xs:rezept>

	<!-- 2 Rezept: Schoko-kuchen -->
	<xs:rezept>
		<xs:rezept-id>505</xs:rezept-id>
		<xs:title>Lenchen’s Schokoladenkuchen</xs:title>
		<xs:autor>Leen</xs:autor>
		<xs:date>2001-11-10T11:45:00</xs:date>
		<xs:picture
			xs:uri="http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/8082-960x720-lenchen_s_schokoladenkuchen.jpg" />

		<xs:ingrediens xs:portion="16">
			<xs:ingredient xs:name="Butter" xs:amount="12.5"
				xs:unit="g"></xs:ingredient>
			<xs:ingredient xs:name="Schokolade, Blockschokolade"
				xs:amount="200" xs:unit="g"></xs:ingredient>
			<xs:ingredient xs:name="Mehl" xs:amount="120" xs:unit="g"></xs:ingredient>
			<xs:ingredient xs:name="Backpulver" xs:amount="1.5"
				xs:unit="TL"></xs:ingredient>
			<xs:ingredient xs:name="Vanillezucker" xs:amount="1"
				xs:unit="Pkt"></xs:ingredient>
			<xs:ingredient xs:name="Eier" xs:amount="4"></xs:ingredient>
		</xs:ingrediens>

		<xs:preparation>
			<xs:arbeitszeit> ca. 1 std</xs:arbeitszeit>
			<xs:schwierigkeitsgrad>Normal</xs:schwierigkeitsgrad>
			<xs:brennwert>295 kcal</xs:brennwert>
			<xs:step>Butter und Schokolade im Wasserbad schmelzen.</xs:step>
			<xs:step>Eier trennen und Eiweiß steif schlagen.</xs:step>
			<xs:step>Eigelbe, Zucker und Vanillezucker verrühren.</xs:step>
			<xs:step>Geschmolzene Butter-Schokomasse hinzufügen und mischen.</xs:step>
			<xs:step>Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben.</xs:step>
			<xs:step>Eine gut gefettete Form geben.</xs:step>
			<xs:step>Bei 180°Grad 40 – 50 Minuten backen.</xs:step>
		</xs:preparation>


		<xs:comment>
			<xs:autor>swieselchen</xs:autor>
			<xs:date>2002-02-07T10:05:00</xs:date>
			<xs:text>Habe Deinen Kuchen gestern gebacken (kleine Abwandlung: statt Blockschokolade hatte ich nur Kuvertüre, zartbitter und ich habe noch etwas Rumaroma und eine Prise Salz dazugegeben) mein LAG war total begeistert. Ich übrigends auch, super rezept.</xs:text>
			<xs:picture xs:uri="http://static.chefkoch-cdn.de/ck.de/user/5ab77fec95e69919037a2ea283c4d6a6.jpg" />
		</xs:comment>
	</xs:rezept>
	
</xs:collection>
=======
<rezept>
  <title>Lenchen’s Schokoladenkuchen</title>
	<autor>Leen</autor>
	<date>15.11.2001</date>	
	 <pictures>
        	<picture uri = "http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/8082-960x720-lenchen_s_schokoladenkuchen.jpg"/>
    </pictures>
	<ingrediens portion="16">
		<ingredient name="Butter" amount="12.5" unit="g"></ingredient>	
		<ingredient name="Schokolade, Blockschokolade" amount="200" unit="g"></ingredient>
		<ingredient name="Mehl" amount="120" unit="g"></ingredient>
		<ingredient name="Backpulver" amount="1/2" unit="TL"></ingredient>
		<ingredient name="Vanillezucker" amount="1" unit="Pkt"></ingredient>		
		<ingredient name="Eier" amount="4"></ingredient>
	</ingrediens>
	
	<preparation>
		<arbeitszeit> ca. 1 std</arbeitszeit>
		<schwierigkeitsgrad>Normal</schwierigkeitsgrad>
		<brennwert>295 kcal</brennwert>
		<step>Butter und Schokolade im Wasserbad schmelzen.</step>
		<step>Eier trennen und Eiweiß steif schlagen.</step>
		<step>Eigelbe, Zucker und Vanillezucker verrühren.</step>
		<step>Geschmolzene Butter-Schokomasse hinzufügen und mischen.</step>
		<step>Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben.</step>
		<step>Eine gut gefettete Form geben.</step>
		<step>Bei 180°Grad 40 – 50 Minuten backen.</step>
	</preparation>
	<comments>
		<comment>
			<autor>swieselchen</autor>
			<date>07.02.2002</date>
			<text>Habe Deinen Kuchen gestern gebacken (kleine Abwandlung: statt Blockschokolade hatte ich nur Kuvertüre, zartbitter und ich habe noch etwas Rumaroma und eine Prise Salz dazugegeben) mein LAG war total begeistert. Ich übrigends auch, super rezept.</text>
			<picture uri = "http://static.chefkoch-cdn.de/ck.de/user/5ab77fec95e69919037a2ea283c4d6a6.jpg"/>	
		</comment>
		<comment>
			<autor>Mane</autor>
			<date>07.01.2003</date>
			<text>Habe ihn eben gebacken und bin begeistert.Super rezept :-) LG Mane</text>
			<picture uri = "http://static.chefkoch-cdn.de/ck.de/user/9029c94d48d6ef778a21f5284bfa2667.jpg"/>		
		</comment>
	</comments>
</rezept>
